# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_jUt_j3lTDVKaZYAwzM05wnaf68JojD

##  **Python Basics**

**print statement**
"""

# string values is in "" ''  and """""" for multiline print sentences
print("hello")
print(''' hello
                       world ''')
print( 123456)

print ('it's going to rain today')

print ('it\'s going to rain today')

print ("it's going to rain today")

"""**comments**"""

#  in this page i will see two numbers
# single line comment
''' doulple line and
multiple
lines
comments'''

"""**variables **"""

# placeholder
# case sensitive
# make shorw no space  * even number *.. can use _ under score  even_number
# can not  be start with number 12334 but can be * num1 num_2 * and special number @%$
a=12
print(a)

a="hello"
print(a)

"""**Data types and user input**"""

# user input
name =input ("enter your name : ")
print(name)

age =int(input ("enter your age : "))
print(age)

# string
# default enter value in string
# floating poits 0.234, 23.5 if the user can gives value in decimal

lenght =float(input ("enter your lenght"))
print(lenght)

ep1=eval(input("enter your ep1 "))
print(ep1)

ep1=eval(input("enter your ep1 "))
print(ep1)

"""**typecastig and subtypes**"""

# conversion of one datatype to another is called type-casting

name="jon"
print (type(name))

# Implicit type casting convertion : where python itself converts one datatype to another
# Explicit type casting convertion : where the user converts one data to another

# Implicit
a=123
b=1.234
print(type(a)) # int
print(type(b)) # float
c=a+b
print(c)
print(type(c)) # float

a="123" # throw an error so we use explicit typecasting in it
b=1.234
print(type(a)) # int
print(type(b)) # float
c=a+b
print(c)
print(type(c)) # float

a="1245"
b=1.234
print(type(a)) # string
print(type(b)) # float
a=int(a)
print("After convertion a is ",type(a))
c=a+b
print(c)
print(type(c)) # float

"""**operators and operands**"""

# operators
# + - * / % // **
# // floor division
# ** power

# Arithmetic operator
a=4
b=2
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b) # without point value
print(a**b)

# comparison operators
print (a==b)
print (a!=b)
print (a>b)
print (a<b)
print (a>=b)
print (a<=b)

# logical operators
print(a==b and a>b)
print(3==3 and 8>7)
print(a==b or a>b)
print(not a==b)
print (not (3==3 and 8>7))

# Assignmet operators
# for asign value
score=0
score=score+1
print(score)
score+=1
print(score)
score-=1
print(score)
score*=2
print(score)
score/=2
print(score)
score%=2
print(score)

# Identity Operators
# types of identity operators
# is
# is not

a=123 # int
b="123" #string
print(a is b)
print(a is not b)

a=123
b=123
print(a is b)
print(a is not b)

# bitwise operators
# 0 1  off on
# << >> & | ^ ~

print(bin(10))
print(bin(15))

a=10
b=8
print(a&b) # AND
print(a|b) # OR
print(a^b) # XOR
print(~a)
print(a<<2) # zero fill right shift --- add vlues  in right
print(a>>1)# zero fill  left shift  -- cut value form right and add values in left

# membership operators
# check the presence of a value in a sequence
# in
# not in
a="helllo"
print("h" in a)
print("h" not in a)

"""**conditional statements**"""

# if statement
a=10
if a>3:
  print("a is greater than 3")

marks =87
if marks >=90:
  print("you will get phone grade")

print("thankyou for joining")

marks=87
if marks >=90:
  print("you will get phone grade")
else: # no condition with else
  print("you will not get phone grade")

print("thankyou for joining")

# if - elif - else
marks =87
if marks >=90:
  print("you will get A grade")
elif marks >=80:
  print("you will get B grade")
elif marks >=70:
  print("you will get C grade")
elif marks >=60:
  print("you will get D grade")
else:
  print("fail")

# nested if

if marks>=80:
  print("you will get a new phone ")
  if marks >=90:
    print("you can go to a trip ")
else :
  print ("you will not get a nothing ")

# short hand if statement
marks=87
if marks>=80: print("you will get a new phone ")
# short hand if else statement
print("you will get a new phone ") if marks>=80 else print("you will not get a nothing ") # no colon in it

"""# *problem solving*

**write a program to display a person's name,age and address in three different lines**
"""

name="jon"
age =21
address="london"
print(name)
print(age)
print(address)

"""**write a profram to swap two variables**"""

a=2
b=3
# method b temperory variable temp
temp=a
a=b
b=temp
print("value of a : ",a)
print( "value of b : ",b)
# method 2
a=30
b=40
a,b=b,a
print("value of a : ",a)
print( "value of b : ",b)

"""**write a program to convert a float into integer**"""

x=122.4
print(type(x))
x=int(x)
print(type(x))
print(x)

"""**write a program to take details from a student for ID-card and then print in different lines**"""

print ("student identity card ")
name =input ("enter your name :")
age =int(input ("enter your age :"))
address=input("enter your address :")
email=input("enter your email :")
print("name : ",name)
print("age : ",age)
print("address : ",address)
print("email : ",email)

"""**write a program to take an user input as integer then convert to float**"""

a=int(input("enter a number :"))
print(type(a))
a=float(a)
print(type(a))
print(a)

"""<!-- place holders -->

**write a program to check if a number is positive**
"""

num=int(input("enter a number :"))
if num>0:
  print("number is positive")
else:
  print("number is negative")

"""**write a program to check whether a number is odd and even**"""

num=int(input("enter a number :"))
if num%2==0:
  print("number is even")
else:
  print("number is odd")

"""**write a program to create area calculator**"""

print("++++ AREA CALCULATOR ++++++")
print("press 1 for area of circle")
print("press 2 for area of rectangle")
print("press 3 for area of triangle")
choice=int(input("enter your choice :"))
if choice==1:
  radius=float(input("enter radius :"))
  area=3.14*radius*radius
  print("area of circle is : ",area)
  print("thank you for using area calculator")

elif choice==2:
  length=float(input("enter length :"))
  breadth=float(input("enter breadth :"))
  area=length*breadth
  print("area of rectangle is : ",area)
  print("thank you for using area calculator")

elif choice==3:
  base=float(input("enter base :"))
  height=float(input("enter height :"))
  area=0.5*base*height
  print("area of triangle is : ",area)
else :
  print("invalid choice")

"""**write a program check whether the passed letter is a vowel or not**"""

if (letter in "aeiou") or (letter in "AEIOU") :
  print("letter is vowel")
else:
  print("letter is not vowel")

"""**write a program to check if a number is a single digit number , 2 digit number and so on ..., up to 5 digit**"""

num =int (input("enter a number :"))
if num<10:
  print("single digit number")
elif num<100:
  print("two digit number")
elif num<1000:
  print("three digit number")